annotations_out: ../data/testing_annotations/labels_household_object_detection_resized.json
ann_path: ../data/testing_annotations/labels_household_object_detection_newest.json
images_path: ../data/home_interior_images/
background_images_path: ../data/background_imgs/
background_max_size: 700
original_max_size: 1000